ts-shim.d.ts

chore: delete unused .d.ts file

---

assets/css/splash.css
pages/index.vue

Nicky and Ethan said we put the tagline up and ask people if its actually a thing. Its responsive I checked, everything else works as well (animations and stuff).

brand: change quento tagline

---

layouts/main.vue
screens/UserGuideModal.vue
store/userGuide.ts
types/user.ts
utils/store-accessor.ts

New user modal

---

components/NotesSidebar.vue
components/SubjectsDropdown.vue
screens/UserInformationModal.vue
types/subjects.ts

Moves the subject select code to its own component, use v-bind:value.sync to get live data and sync state between parent and child.
Closes #43

Subject select component

---

components/NotesCard.vue

1. Title repositioned and size increased
2. Pills repositioned
3. Content fade added on bottom
4. Scrollbar redesigned

Notes Design Changes 

---

assets/scss/components/notes_md.scss
assets/scss/main.scss
components/NotesCard.vue

feat: notes styles

---

assets/scss/components/modal.scss
assets/scss/main.scss
components/NotesCard.vue
pages/Notes.vue
pages/notes/index.vue
screens/EditNotesModal.vue
screens/PostNotesModal.vue
screens/PreviewNotesModal.vue
store/notes.ts
types/notes.ts

Edit notes

---

mixins/UserMixin.ts
screens/UserGuideModal.vue
screens/UserInformationModal.vue
static/sw.js
store/auth.ts
store/notes.ts
store/suggestions.ts
store/userGuide.ts

fixes issue where User Info popup appears briefly when page loads because the user data hasn't loaded fully yet - disables user info popup before user data loads

User mixin

---

components/NotesSidebar.vue
store/notes.ts

Filter fix

---

types/schools.ts

feat: update schools lsit

---

assets/scss/components/notes_md.scss
components/DeleteNotesModal.vue
components/NotesCard.vue
store/notes.ts

NOT FINISHED - Allows users to delete ONLY NOTES - needs testing

feat: delete notes option

---

middleware/router-auth.ts
pages/auth/SignUp.vue
pages/user/discord.vue
pages/user/profile.vue
types/user.ts

@Vansh-Sethi was dividing by 200 but its in  percentage so you need to multiply by 100 again -> should be divide by 2.
Broken: 
Fixed:

User exp fix

---

components/Sidebar.vue
pages/Suggestions.vue
pages/questions/index.vue
screens/questions/PostQuestionModal.vue

1. Color changes (Post suggestion button, question button, sidebar)
2. Post new question modal changed

color changes and post new question modal changes

---

pages/newsletters/_id.vue

1. Added back button to newsletters

added back button to newsletters

---

components/NotesCard.vue
static/firebase-auth-sw.js

Content on notes (text, links) were unclickable/unhighlightable because of a hidden div above the notes which wasn't removed. 
Divs were removed

Unclickable note bug

---

assets/scss/main.scss
components/TopNav.vue
middleware/router-auth.ts
mixins/UserMixin.ts
pages/questions/_id.vue
pages/user/edit.vue
pages/user/profile.vue
plugins/firebaseFunctions.ts
screens/UserInformationModal.vue
screens/notes/PostNotesModal.vue
screens/questions/PostQuestionModal.vue
static/firebase-auth-sw.js
store/auth.ts
store/questions.ts
store/suggestions.ts
types/subjects.ts
types/user.ts

- Ability to change name
- Ability to change bio
- Ability to change grade & school
- Ability to change profile picture 
**Desktop View**
**Mobile View**

Editable profile page

---

components/AvatarBar.vue
components/NotesCard.vue
components/QuestionCard.vue
middleware/router-auth.ts
pages/user/edit.vue
pages/user/profile.vue
pages/user/view/_id.vue

- Ability to click on avatar's and route to person's own page
example:
Video of it working (below)
https://gyazo.com/857aa87ac9825f8a0a04f9655ff878d8

Added viewable profile

---

components/TopNav.vue
layouts/main.vue
middleware/router-auth.ts
mixins/AuthenticationMixin.ts
pages/Coming-Soon.vue
pages/auth/verify-email.vue
screens/UserInformationModal.vue
store/auth.ts
store/userGuide.ts

Email verification is now implemented - to test, create an account with email password with email you haven't already linked, and then follow the steps -> if they are clear enough for new users, that should be enough explanation from the steps by themselves.

feat: email auth verification, watch user auth state redirects

---

components/NotesSidebar.vue
pages/auth/verify-email.vue
store/notes.ts
types/notes.ts
types/subjects.ts

Uses likes + views + recency to index notes, not perfected yet, algorithm will be improved + add personalization

Sort by popular

---

types/subjects.ts

Adds gym as fav subject, fixes #247

feat: add phy ed as a favouritable subject

---

assets/scss/vuexy/_customClasses.scss
assets/scss/vuexy/layout/_layoutCommon.scss
assets/scss/vuexy/layout/_theNavbar.scss
components/NotesListCard.vue
components/NotesSearchBar.vue
components/TopNav.vue
layouts/main.vue
pages/notes/_id.vue
pages/notes/index.vue
pages/questions/index.vue
plugins/algolia.ts
store/window.ts
types/firebaseTypes.ts
types/notes.ts

Add search bar to notes, UI is still a bit scrappy but will be improved as part of frontend week 2 goals

feat: add search bar for notes

---

assets/scss/components/notes_md.scss
components/VsTextarea.vue
screens/notes/EditNotesModal.vue

Multi line code fix

---

components/FilterSidebar.vue
components/NotesCard.vue
mixins/UserMixin.ts
pages/notes/index.vue
pages/questions/index.vue
pages/user/discord.vue
store/auth.ts
store/notes.ts
store/questions.ts
store/userGuide.ts
store/window.ts
types/interface.ts
types/subjects.ts

Questions Page now has filtering and standard layout

feat: rewrite questions index page to be standard layout

---

pages/questions/index.vue
store/questions.ts

Adds personalization to questions feed as well

feat: personalized questions feed

---

components/QuestionCard.vue
pages/Home.vue
store/feeds.ts

YEEE combined feed for notes + questions (which is personalized) on the homepage

feat: combined notes and questions personalized feed

---

components/Sidebar.vue

Renamed newsletter on the sidebar to updates as per raymonds request

feat: rename newsletters on sidebar to updates

---

assets/scss/components/modal.scss
components/FilterSidebar.vue
pages/groups/discover.vue
pages/groups/g/_id/groupNotes.vue
pages/groups/g/_id/groupQuestions.vue
pages/groups/index.vue
screens/groups/NewGroupsModal.vue
store/feeds.ts
store/notes.ts
store/questions.ts

fix: groups cards on discover shrinking

---

assets/scss/main.scss
assets/scss/vuexy/_customClasses.scss
components/CategoryPills.vue
components/NotesCard.vue
components/QuestionCard.vue
components/ResponseCard.vue
mixins/IconMixin.ts
pages/questions/_id.vue

feat: category pills and better question card padding

---

assets/scss/vuexy/_typography.scss
assets/scss/vuexy/_variables.scss
components/DeleteNotesModal.vue
components/GroupsCard.vue
components/QuestionCard.vue
components/ResponseCard.vue
components/TopNav.vue
mixins/AuthenticationMixin.ts
pages/Home.vue
pages/Suggestions.vue
pages/auth/verify-email.vue
pages/groups/discover.vue
pages/groups/g/_id.vue
pages/groups/g/_id/index.vue
pages/groups/index.vue
pages/notes/index.vue
pages/questions/_id.vue
pages/user/edit.vue
pages/user/profile.vue
pages/user/view/_id.vue
plugins/vuesax.ts
screens/SuggestionModal.vue
screens/groups/groupCreateModal.vue
screens/notes/PreviewNotesModal.vue
screens/questions/PreviewQuestionModal.vue
typings/quento.d.ts
typings/shims-vue.d.ts

Notification plugin + notification colors

Standardize vs notify

---

components/NotesCard.vue
components/TopNav.vue
mixins/PasteImagesMixin.ts
pages/groups/g/_id/notes.vue
pages/notes.vue
pages/notes/_id.vue
pages/notes/index.vue
screens/notes/EditNotesModal.vue
screens/notes/PostNotesModal.vue
screens/notes/PreviewNotesModal.vue
store/notes.ts
types/notes.ts

Edit screen
